# Generated by Django 4.1.2 on 2022-10-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='text',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='published_date',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
