# Generated by Django 4.1.2 on 2022-10-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default=''),
        ),
    ]
