# Generated by Django 4.1.7 on 2023-03-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_price',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.URLField(default=None),
        ),
    ]
