# Generated by Django 4.2.6 on 2023-10-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
