# Generated by Django 4.2.6 on 2023-11-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mail_has_been_sent',
            field=models.BooleanField(default=False),
        ),
    ]
